
  <META http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <link rel="stylesheet" media="screen" type="text/css" href="/Shared/menu.css">
    <link rel="stylesheet" media="screen" type="text/css" title="tiOPF Default" href="/Shared/tiopf.css">
    <link rel="stylesheet" media="screen" type="text/css" href="/Shared/SyntaxHighlighter.css">

<!-- A IE hack to fix it's shortcomings of web standards 
     IE doesn't support the :hover on any other element other
     that a link. We need this bit of script it fix that flaw.  -->
    <script type='text/javascript' src='/Shared/IEhack.js'></script>
